import LocalizedStrings from 'react-native-localization';

export const strings = new LocalizedStrings({
  en_US: {
    home: 'Home',
    subjects: 'Subjects',
    tasks: 'Tasks',
    schedule: 'Schedule',
    all: 'All',
    archived: 'Archived',
    completed: 'Completed',
    new: 'New',
    newSubject: 'New subject',
    newTask: 'New task',
    newEvent: 'New event',
    editSubject: 'Edit subject',
    editTask: 'Edit task',
    editEvent: 'Edit event',
  },
  ru_RU: {
    home: 'Главная',
    subjects: 'Предметы',
    tasks: 'Задачи',
    schedule: 'Расписание',
    all: 'Все',
    archived: 'Архивированные',
    completed: 'Завершенные',
    new: 'Новые',
    newSubject: 'Новый предмет',
    newTask: 'Новая задача',
    newEvent: 'Новое событие',
    editSubject: 'Изменить предмет',
    editTask: 'Изменить задачу',
    editEvent: 'Изменить событие',
  },
});
